# Generated by Django 4.2.6 on 2023-10-24 13:30

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.StructBlock([('heading_text', wagtail.blocks.CharBlock(required=True)), ('heading_size', wagtail.blocks.ChoiceBlock(blank=True, choices=[('', 'Select a heading size'), ('h2', 'H2'), ('h3', 'H3')], required=False))])), ('paragraph', wagtail.blocks.RichTextBlock(blank=True)), ('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('caption', wagtail.blocks.CharBlock(required=False))]))], blank=True, use_json_field=True, verbose_name='Post content'),
        ),
    ]
