# Generated by Django 4.2.6 on 2023-10-23 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='homepage_cta',
            field=models.CharField(default='Read Latest Posts', help_text='Text to display for Homepage Call to Action', max_length=255, verbose_name='Homepage CTA'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='homepage_cta_link',
            field=models.ForeignKey(blank=True, help_text='Choose a page to link to for the Homepage Call to Action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Homepage CTA link'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='homepage_text',
            field=models.CharField(default='Here, I write about all things tech, accessibility and advocacy.', help_text='Write an introduction for the blog', max_length=255),
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_suffix', models.CharField(default='PraizTech Blog', help_text="The suffix for the title meta tag i.e. ' - PraizTech Blog'", max_length=255, verbose_name='Title suffix')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
