# Generated by Django 4.2.6 on 2023-10-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_homepage_image_delete_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='homepage_cta',
            field=models.CharField(blank=True, help_text='Text to display for Homepage Call to Action', max_length=255, null=True, verbose_name='Homepage CTA'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='homepage_text',
            field=models.CharField(blank=True, help_text='Write an introduction for the blog', max_length=255, null=True),
        ),
    ]
