# Generated by Django 4.2.6 on 2023-10-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_homepage_cta_homepage_cta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='heading',
            field=models.CharField(blank=True, help_text='The heading for the homepage', max_length=255, null=True),
        ),
    ]
