# Generated by Django 4.2.6 on 2023-10-27 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_heading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='cta_link',
            new_name='cta_link_page',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='cta',
            new_name='cta_text',
        ),
    ]
